image: ubuntu

stack: go 1.11.2

environment:
  GO111MODULE: on
  matrix:
    - GOOS: linux
    - GOOS: darwin
    - GOOS: windows
      EXE: .exe

matrix:
  fast_finish: true

before_build:
  - go mod download
  - mkdir -p .build

build_script:
  - export CHANGELOG=$(git log ${APPVEYOR_REPO_TAG_NAME}^..$APPVEYOR_REPO_TAG_NAME --pretty=format:'<li> <a href="http://github.com/daehlith/sync-fork/commit/%H">view commit &bull;</a> %s</li> ' --reverse | tr '\n' ' ')
  - go build -o .build/${APPVEYOR_PROJECT_NAME}-${GOOS}-amd64${EXE} cmd/sync-fork/main.go

artifacts:
  - path: .build/*-amd64*
    name: Releases

before_deploy:
  - echo Changelog = ${CHANGELOG}
deploy:
  - provider: GitHub
    force_update: true
    description: |
      ### Changes:
      ${CHANGELOG}
    artifact: /.*-amd64.*/
    auth_token:
      secure: NYUKWXN19TyDSzpzHb1UePVAfbIpKpQcNZWMKJCObtHQ7d+ccGeso7fesC4XNhS6
    draft: false
    prerelease: false
    on:
      branch: master
      APPVEYOR_REPO_TAG: true
