image: ubuntu

stack: go 1.11.2

environment:
  GO111MODULE: on
  matrix:
    - GOOS: linux
    - GOOS: darwin
    - GOOS: windows
      EXE: .exe

matrix:
  fast_finish: true

before_build:
  - go mod download
  - mkdir -p .build
  - sh: export CHANGELOG=$(git log $(git describe --abbrev=0 --tags "${APPVEYOR_REPO_TAG_NAME}^")..$APPVEYOR_REPO_TAG --pretty=format:'<li> <a href="http://github.com/daehlith/sync-fork/commit/%H">view commit &bull;</a> %s</li> ' --reverse | while read line; do echo -n "$line "; done)

build_script:
  - echo "changelog = ${CHANGELOG}"
  - echo "tag name = ${APPVEYOR_REPO_TAG_NAME}"
  - echo "binary name = ${APPVEYOR_PROJECT_NAME}-${GOOS}-amd64${EXE}"
  - go build -o .build/${APPVEYOR_PROJECT_NAME}-${GOOS}-amd64${EXE} cmd/sync-fork/main.go
  - ls -al .build

artifacts:
  - path: .build/*-amd64*
    name: Releases

before_deploy:
  - export CHANGELOG=$(git log $(git describe --abbrev=0 --tags "${APPVEYOR_REPO_TAG_NAME}^")..$APPVEYOR_REPO_TAG --pretty=format:'<li> <a href="http://github.com/daehlith/sync-fork/commit/%H">view commit &bull;</a> %s</li> ' --reverse | while read line; do echo -n "$line "; done)
deploy:
  description: ${CHANGELOG}
  provider: GitHub
  artifact: /.*-amd64.*/
  auth_token:
    secure: NYUKWXN19TyDSzpzHb1UePVAfbIpKpQcNZWMKJCObtHQ7d+ccGeso7fesC4XNhS6
  draft: false
  prerelease: false
  on:
    tag: ${APPVEYOR_REPO_TAG_NAME}
