name: Build
on: [push]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - os: macos-latest
            GOOS: darwin
            GOARCH: amd64
            SUFFIX: ""
          - os: ubuntu-latest
            GOOS: linux
            GOARCH: amd64
            SUFFIX: ""
          - os: windows-latest
            GOOS: windows
            GOARCH: amd64
            SUFFIX: .exe
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: setup Go
        uses: actions/setup-go@v1
        with:
          go-version: "1.15.x"
      - name: lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.35
      - name: compile
        run: go build -o .build/sync-fork-${{matrix.GOARCH}}-${{matrix.GOOS}}${{matrix.SUFFIX}} cmd/sync-fork/main.go